# Generated by Django 6.0.6 on 2026-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=10)),
                ('pref', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('aging_rate', models.FloatField()),
                ('area_type', models.CharField(max_length=10)),
            ],
        ),
    ]
